### ISSUE TITLE
Error en pantalla de login

### ISSUE THREAD

**Issue by FedericoQuarin** [BarApp-Chort-Quarin-Reynoso/BarApp-Mobile#35]
Al probar a loggearme en la app usando el celular, el login tarda mas. No hay ningun feedback de que este verificado las credenciales mientras tanto, y si clickeo varias veces aparece varias veces el Dialog de error.

**Comment by ChortJulio** [comment]
Siento que el PR mergeado puede haber solucionado este issue. El tema es que la descripción no fue muy precisa, y al hablar con Federico no fue capaz de darme una descripción más concisa. Por ahora quedará cerrado.
