### ISSUE TITLE
Agregar pantallas de carga a la aplicacion

### ISSUE THREAD

**Issue by FedericoQuarin** [BarApp-Chort-Quarin-Reynoso/BarApp-Mobile#54]
Hay muchos lugares de la aplicación donde hay mucha demora en realizar la busqueda (por ejemplo, pantalla de inicio para buscar los bares). Deberia mostrarse al usuario algun proceso de carga e informarle si ocurre algun tipo de error. 
Se podria probar a implementar Skeleton en todas donde corresponda.

**Comment by ChortJulio** [comment]
Done in #90
