### ISSUE TITLE
Agregar recuperar contraseña

### ISSUE THREAD

**Issue by FedericoQuarin** [BarApp-Chort-Quarin-Reynoso/BarApp-Mobile#6]
Agregar la funcionalidad de recuperar la contraseña

**Comment by Valenreynoso17** [comment]
La plantilla de Firebase Auth ya está lista, falta agregar la acción en el boton de ¿Olvidaste tu contraseña? (Y crear el boton si no existe todavía)

**Comment by ChortJulio** [comment]
Done in #81 by @Valenreynoso17
