### ISSUE TITLE
Reservar desde la pantalla Favoritos inconsistente

### ISSUE THREAD

**Issue by FedericoQuarin** [BarApp-Chort-Quarin-Reynoso/BarApp-Mobile#75]
Al acceder a un bar desde favoritos y realizar una reserva, la misma se almacena en Firestore con un idRestaurante que no se corresponde con el bar real. Al acceder a la busqueda desde algun otro recycler o la pantalla del mapa, la reserva funciona correctamente.

### Pasos para replicar
- Logearse con cualquier usuario en mobile
- Logearse con cualquier usuario BAR en web
- Desde mobile, acceder al bar logeado desde algun carrusel del inicio y realizar una reserva
- Desde mobile, acceder al bar logeado desde favoritos y realizar una reserva (solo lo probe realizando una reserva para el mismo dia, aunque dudo que haya diferencia)
- En la pantalla Reservas deberian mostrarse correctamente ambas reservas
- En la pagina web, deberia aparecer solo una reserva, la que tiene el id correcto

**Comment by ChortJulio** [comment]
Es fácil de resolver por suerte! Simplemente tienes que usar el Helper de /utils para consultar si es un RestauranteUsuario y, en ese caso, utilizar la propiedad **.idRestaurante** en vez de **.id**, ya que sino la Reserva se creará anexado al idRestaurante del restaurante favorito y/o restaurante visto recientemente.
