### ISSUE TITLE
Corregir pantalla resultado busqueda

### ISSUE THREAD

**Issue by FedericoQuarin** [BarApp-Chort-Quarin-Reynoso/BarApp-Mobile#84]
Revisar que este todo ok en esta pantalla. Algunos de los errores a corregir son:
- El layout de filtro se ve en mitad de la pantalla cuando hay pocos resultados
- No se ni si andan los filtros
- Las cards son inconsistentes (como el boton de favoritos)

**Comment by ChortJulio** [comment]
Done in #92
